### ISSUE TITLE
Input > Text area > Text Area With Auto Grow doesn't seem to work on Firefox

### ISSUE THREAD

**Issue by mpressen** [lazaronixon/css-zero#1]
Checking this library, I think I spotted a bug on : https://csszero.lazaronixon.com/lookbook/inspect/input/text_area

Using Firefox as my web browser (v.131.0 on ubuntu 24.04), Text Area With Auto Grow seems to have exactly the same behaviour than Text Area.

Here is a screenshot :
![image](https://github.com/user-attachments/assets/de350ad4-8995-4330-a76a-697702930689).

Thanks a lot for all your work.

**Comment by lazaronixon** [comment]
This is the expected behaviour, you can see in the notes tabs: "Text area with auto grow is not supported in [all browsers](https://caniuse.com/mdn-css_properties_field-sizing)."
