### ISSUE TITLE
Open Props 

### ISSUE THREAD

**Issue by matthewblott** [lazaronixon/css-zero#10]
The CSS files look almost identical to the [Open Props](https://github.com/argyleink/open-props) project. Wouldn't it be better to build something around that or am I missing something?

**Comment by lazaronixon** [comment]
You're right. It has many things in common with open props. In the same way, it has many things in common with Tailwind and Shadcn. In addition to "Open Props" variables, we have utility classes and pre-build components:

Check this out: https://csszero.lazaronixon.com
