### ISSUE TITLE
Conflict with Doorkeeper

### ISSUE THREAD

**Issue by matthew-levan** [lazaronixon/css-zero#11]
I've used `css-zero` happily until installing the Doorkeeper gem into my Rails app. Doorkeeper uses Sprockets to add Bootstrap and some of their own custom CSS to the application's assets pipeline, but, unfortunately, some of this CSS (I'm not sure if Bootstrap or their custom CSS) conflicts with `css-zero`'s and makes the rendered pages look horrible. Any suggestions for ameliorating this issue? I'm running a Rails 8 app that uses Propshaft.

**Comment by lazaronixon** [comment]
It's the behavior with Propshaft when you use `<%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>`. 

You can import the files individually instead and only import doorkeeper when it's needed:

Replace:

```html
<%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
```

With:

```html
<%= stylesheet_link_tag "_reset", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "animations", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "borders", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "colors", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "effects", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "filters", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "sizes", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "transform", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "transition", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "typography", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "zutilities", "data-turbo-track": "reload" %>
```

ps: Hey why are you using doorkeeper when you have [authentication-zero]https://github.com/lazaronixon/authentication-zero) 😝

**Comment by matthew-levan** [comment]
Hey thanks for the quick reply! Just loading each CSS file with your suggestion in the first comment worked. Thank you.

Re: not using `authentication-zero`, I would if it helped with making my server into an OAuth2 and OIDC provider, which is why I'm using Doorkeeper. For this project, I used Rails 8's authentication generator as a base and then implemented an Ethereum wallet authentication flow and a passkey authentication flow on top.
