### ISSUE TITLE
Select doesn't render properly in layouts other than desktop

### ISSUE THREAD

**Issue by ravibhusal** [lazaronixon/css-zero#12]
**Phone**
![image](https://github.com/user-attachments/assets/79dd4b70-1a8a-434a-8d4b-29909d227a47)

**Tablet**
![image](https://github.com/user-attachments/assets/d942b95e-537c-4cc2-9da7-90494ca31195)

**Comment by lazaronixon** [comment]
Hey whats up... this is the expected behaviour, on mobile it should render the native picker. For more details check https://tom-select.js.org/

**Comment by ravibhusal** [comment]
Thanks! Loving this gem btw! 💯
