### ISSUE TITLE
Tabs : Active Tab on hover becomes unreadable

### ISSUE THREAD

**Issue by mpressen** [lazaronixon/css-zero#2]
On firefox / ubuntu, when I'm hovering an active tab (or after clicking on an inactive tab), its background becomes white while the text stays white, it is therefore unreadable.
https://csszero.lazaronixon.com/lookbook/inspect/tabs/default 
![image](https://github.com/user-attachments/assets/8a84987f-29cc-43b0-a04e-90fb158e358f)

**Comment by lazaronixon** [comment]
That's interesting. I don't see this issue on OSX Firefox. I'll take a look.

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/css-zero/commit/7f90cc29c2c5f5ce59f4e46ec792995a022ba1ff
