### ISSUE TITLE
error  css_zero [not found]

### ISSUE THREAD

**Issue by ac74394** [lazaronixon/css-zero#5]
Hello - on a new Rails 8 app, I add the css-zero gem to gem file and bundle,
next, I run the generator:

% bin/rails generate css_zero:install
      create  app/assets/stylesheets/base.css
       force  app/views/layouts/application.html.erb
      create  app/assets/stylesheets/layouts.css
      create  app/assets/images/menu.svg
      create  app/assets/stylesheets/input.css
      create  app/assets/images/select-arrow.svg
      create  app/assets/stylesheets/switch.css
      create  app/assets/stylesheets/button.css
      create  app/assets/images/loader-circle.svg
      create  app/assets/stylesheets/flash.css
      create  app/javascript/controllers/element_removal_controller.js
      create  app/assets/stylesheets/alert.css

However, when I create a basic controller, I get an error that css_zero is not found.

% rails generate controller css_sample home
      create  app/controllers/css_sample_controller.rb
       route  get "css_sample/home"
       error  css_zero [not found]
      invoke  test_unit
      create    test/controllers/css_sample_controller_test.rb
      invoke  helper
      create    app/helpers/css_sample_helper.rb
      invoke    test_unit

The CSS files created by the generator are in the app/assets/stylesheets directory.

Help is greatly appreciated and I think this looks like an awesome project and can"t wait to start using it!

**Comment by lazaronixon** [comment]
Hey, thanks for reporting that; it's fixed on 0.0.64.
https://github.com/lazaronixon/css-zero/releases/tag/v0.0.64

**Comment by ac74394** [comment]
Thank you, and I hope you have a great day!!
