### ISSUE TITLE
Documentation for display theme switch

### ISSUE THREAD

**Issue by jbwl** [lazaronixon/css-zero#6]
I cannot find documentation for switching between light and dark and "system theme".
I would like to implement a switch similar to the theme switch in the css-zero lookbook. Is this out of scope?

**Comment by lazaronixon** [comment]
I had to change the base.css in the showcase to use something like '<html data-theme=dark><html>' because the preview runs inside an iframe. In your application, try something like '<html style="color-scheme: dark"><html>'
