### ISSUE TITLE
popover button appear on top of dialog

### ISSUE THREAD

**Issue by cmyurtsev** [lazaronixon/css-zero#9]
hey @lazaronixon,

I've been playing around with your code a bit and found an issue with stacked popover buttons. When there are multiple buttons stacked, the dialog of the first one seems to appear behind the button of the next popover.

![Screenshot from 2024-11-29 15-22-21](https://github.com/user-attachments/assets/69f977b6-b283-46c7-a4b5-1597f5878954)

Manually setting a z-index on the dialog element works, but perhaps there is a more elegant way to do this? Also this seems to fail when I try to add a popover to a navbar in the header. Here the z-index will not be considered (Perhaps because of the position?)

thanks for your work on this gem, no pun intended!

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/css-zero/releases/tag/v0.0.73
